# Generated by Django 3.0.7 on 2020-06-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('forehand_strength', models.IntegerField(default=50)),
                ('backhand_strength', models.IntegerField(default=50)),
            ],
        ),
    ]
