# Generated by Django 3.0.7 on 2020-06-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublepower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
