# Generated by Django 3.0.7 on 2020-06-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doublepower', '0002_player_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('rank',)},
        ),
    ]
